AWSTemplateFormatVersion: "2010-09-09"
Description: Static site for cost-estimation evaluation
Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: not-deployed-evaluation-static-site
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: site-origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
        Origins:
          - Id: site-origin
            DomainName: not-deployed-evaluation-static-site.s3.amazonaws.com
            S3OriginConfig: {}
